### ISSUE TITLE
Edit > HighlightWords sub-menu is grayed out

### ISSUE THREAD

**Issue by joelmellon** [evandroforks/HighlightWords#2]
Any idea why Edit > HighlightWords sub-menu is grayed out?

<img width="621" alt="Screen Shot 2022-02-03 at 11 58 35 AM" src="https://user-images.githubusercontent.com/13803216/152419428-dc4287b5-3a62-4995-aac0-e24ce9f66e1c.png">

**Comment by evandrocoan** [comment]
Check sublime text console logs on startup. Is there some error on it?

**Comment by joelmellon** [comment]
Does this look like anything?

```
reloading plugin HighlightWords.HighlightWords
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/Lib/python38/sublime_plugin.py", line 312, in reload_plugin
reloading python 3.3 plugin Goto Usage.dep_graph
    m = importlib.import_module(modulename)
  File "./python3.8/importlib/__init__.py", line 127, in import_module
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 808, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "~/Library/Application Support/Sublime Text 3/Installed Packages/HighlightWords.sublime-package/HighlightWords.py", line 7, in <module>
ModuleNotFoundError: No module named 'lark'
```

**Comment by evandrocoan** [comment]
It looks like the same issue as: https://github.com/evandrocoan/HighlightWords/issues/1 - Lark dependency?

**Comment by joelmellon** [comment]
That was it. Thanks so much, you're a legend. 🍻

This is you, right? https://ko-fi.com/evandrocoan

**Comment by joelmellon** [comment]
I spoke too soon. I thought my highlight worked (since I use the color of JSON errors and I tested my keyword in broken JSON, lol) but the console is still throwing errors:

```
Exception in thread Thread-238:
Traceback (most recent call last):
  File "./python3.8/threading.py", line 932, in _bootstrap_inner
  File "./python3.8/threading.py", line 870, in run
  File "~/Library/Application Support/Sublime Text 3/Installed Packages/HighlightWords.sublime-package/HighlightWords.py", line 584, in delayedFix
  File "~/Library/Application Support/Sublime Text 3/Installed Packages/HighlightWords.sublime-package/HighlightWords.py", line 557, in highlightGlobalKeywords
TypeError: 'NoneType' object is not iterable
```

I used your [PackagesControl](https://github.com/evandrocoan/PackagesManager) to re-install HighlightWords as suggested in [#1](https://github.com/evandrocoan/HighlightWords/issues/1#issuecomment-980452878).

Here's my `.../Sublime/Packages/User/HighlightWords.sublime-settings`:

```json
{
	"colors_by_scope":
	[
		"string",
		"entity.name.class",
		"variable.parameter",
		"invalid.deprecated",
		"invalid",
		"support.function"
	],
	"use_regex": false,
	"permanent_highlight_keyword_color_mappings": [
		{
			"keyword": "TODO",
			"color": "source.json.sublime meta.mapping.value.json meta.sequence.json meta.mapping.json invalid.illegal.expected-mapping-key.json ",
		},
	]
}
```

**Comment by evandrocoan** [comment]
Thanks for the coffee. I tried your setting, and it worked: 
![image](https://user-images.githubusercontent.com/5332158/152665788-72560abc-89ff-4a79-a2e4-c70e12513d2d.png)

The code which broke was from Sublime Text API:
![image](https://user-images.githubusercontent.com/5332158/152665810-de8d8e27-4d27-4e55-971f-5b71ef0075f4.png)

I asked Sublime Text to load the setting `permanent_highlight_keyword_color_mappings` from the configuration file, but it did return None instead of your setting.

I tried this in a clean installation and after I installed the package, I got the same error as you:
![image](https://user-images.githubusercontent.com/5332158/152665888-762d087a-4c6d-4b07-af5e-08621ed09558.png)

But after restarting Sublime Text, the problem was fixed:
![image](https://user-images.githubusercontent.com/5332158/152665890-0f892385-a15b-4f4c-9ec6-379440c4654a.png)

I added a protection for this Sublime Text bug. It should be released on the next version of this package. For now, you can try to restart Sublime Text after installing this package.

**Comment by joelmellon** [comment]
Awesome! The restart worked. Thanks very much. 🤘
